import mongoose, { Document, Model, Schema } from 'mongoose';

export interface IInterviewSession extends Document {
  candidate: mongoose.Types.ObjectId;
  interviewer?: mongoose.Types.ObjectId;
  title: string;
  description?: string;
  type: 'technical' | 'behavioral' | 'mixed';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  skills: string[];
  duration: number;
  status: 'scheduled' | 'in-progress' | 'completed' | 'cancelled';
  questions: Array<{
    questionId?: mongoose.Types.ObjectId;
    question: string;
    type: 'technical' | 'behavioral' | 'situational';
    expectedAnswer?: string;
    difficulty: 'beginner' | 'intermediate' | 'advanced';
    answer?: {
      text?: string;
      audioUrl?: string;
      timeSpent?: number;
      submittedAt?: Date;
      timestamp: Date;
    };
    evaluation?: {
      score?: number;
      feedback?: string;
      criteria?: {
        technical_accuracy?: number;
        communication?: number;
        problem_solving?: number;
        confidence?: number;
      };
      strengths?: string[];
      improvements?: string[];
      keywordMatch?: number;
      timeFactor?: number;
      assessedAt?: Date;
      assessedBy?: 'AI' | 'Human';
      aiAnalysis?: {
        sentiment?: string;
        keywords?: string[];
        clarity_score?: number;
        confidence_level?: string;
      };
    };
    timeSpent?: number;
    timeLimit?: string;
    assessmentCriteria?: string[];
  }>;
  overallEvaluation?: {
    totalScore?: number;
    averageScore?: number;
    totalQuestions?: number;
    completedQuestions?: number;
    feedback?: string;
    strengths?: string[];
    improvements?: string[];
    evaluatedAt?: Date;
    evaluatedBy?: 'AI' | 'Human';
    recommendation?: 'strongly_recommend' | 'recommend' | 'neutral' | 'not_recommend' | 'strongly_not_recommend';
  };
  startedAt?: Date;
  completedAt?: Date;
  totalDuration?: number;
  recording?: {
    audioUrl?: string;
    transcription?: string;
  };
  interviewType: 'online' | 'in-person';
  scheduledFor?: Date;
  meetingLink?: string;
  metadata?: {
    userAgent?: string;
    ipAddress?: string;
    location?: string;
    assessmentCriteria?: string[];
    autoGenerated?: boolean;
  };
  createdAt: Date;
  updatedAt: Date;
  calculateAverageScore?(): number;
  sessionDuration?: number;
}

const interviewSessionSchema = new Schema<IInterviewSession>({
  candidate: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  interviewer: {
    type: Schema.Types.ObjectId,
    ref: 'User'
  },
  title: {
    type: String,
    required: [true, 'Interview title is required'],
    trim: true
  },
  description: {
    type: String,
    trim: true
  },
  type: {
    type: String,
    enum: ['technical', 'behavioral', 'mixed'],
    default: 'technical'
  },
  difficulty: {
    type: String,
    enum: ['beginner', 'intermediate', 'advanced'],
    default: 'intermediate'
  },
  skills: [{
    type: String,
    required: true
  }],
  duration: {
    type: Number,
    default: 30
  },
  status: {
    type: String,
    enum: ['scheduled', 'in-progress', 'completed', 'cancelled'],
    default: 'scheduled'
  },
  questions: [{
    questionId: {
      type: Schema.Types.ObjectId,
      auto: true
    },
    question: {
      type: String,
      required: true
    },
    type: {
      type: String,
      enum: ['technical', 'behavioral', 'situational'],
      default: 'technical'
    },
    expectedAnswer: {
      type: String
    },
    difficulty: {
      type: String,
      enum: ['beginner', 'intermediate', 'advanced'],
      default: 'intermediate'
    },
    answer: {
      text: String,
      audioUrl: String,
      timeSpent: Number,
      submittedAt: Date,
      timestamp: {
        type: Date,
        default: Date.now
      }
    },
    evaluation: {
      score: {
        type: Number,
        min: 0,
        max: 10
      },
      feedback: String,
      criteria: {
        technical_accuracy: Number,
        communication: Number,
        problem_solving: Number,
        confidence: Number
      },
      strengths: [String],
      improvements: [String],
      keywordMatch: Number,
      timeFactor: Number,
      assessedAt: Date,
      assessedBy: {
        type: String,
        enum: ['AI', 'Human'],
        default: 'AI'
      },
      aiAnalysis: {
        sentiment: String,
        keywords: [String],
        clarity_score: Number,
        confidence_level: String
      }
    },
    timeSpent: {
      type: Number,
      default: 0
    },
    timeLimit: {
      type: String,
      default: "3"
    },
    assessmentCriteria: {
      type: [String],
      default: ['technical_accuracy', 'communication']
    }
  }],
  overallEvaluation: {
    totalScore: {
      type: Number,
      min: 0,
      max: 10
    },
    averageScore: {
      type: Number,
      min: 0,
      max: 10
    },
    totalQuestions: Number,
    completedQuestions: Number,
    feedback: String,
    strengths: [String],
    improvements: [String],
    evaluatedAt: Date,
    evaluatedBy: {
      type: String,
      enum: ['AI', 'Human'],
      default: 'AI'
    },
    recommendation: {
      type: String,
      enum: ['strongly_recommend', 'recommend', 'neutral', 'not_recommend', 'strongly_not_recommend']
    }
  },
  startedAt: {
    type: Date
  },
  completedAt: {
    type: Date
  },
  totalDuration: {
    type: Number
  },
  recording: {
    audioUrl: String,
    transcription: String
  },
  interviewType: {
    type: String,
    enum: ['online', 'in-person'],
    default: 'online'
  },
  scheduledFor: {
    type: Date
  },
  meetingLink: {
    type: String
  },
  metadata: {
    userAgent: String,
    ipAddress: String,
    location: String,
    assessmentCriteria: [String],
    autoGenerated: Boolean
  }
}, {
  timestamps: true
});

// Indexes for better query performance
interviewSessionSchema.index({ candidate: 1, createdAt: -1 });
interviewSessionSchema.index({ status: 1 });
interviewSessionSchema.index({ skills: 1 });

// Virtual for session duration
interviewSessionSchema.virtual('sessionDuration').get(function(this: IInterviewSession) {
  if (this.startedAt && this.completedAt) {
    return Math.round((this.completedAt.getTime() - this.startedAt.getTime()) / (1000 * 60));
  }
  return null;
});

// Method to calculate average score
interviewSessionSchema.methods.calculateAverageScore = function(this: IInterviewSession) {
  if (this.questions.length === 0) return 0;
  
  const validScores = this.questions
    .filter(q => q.evaluation && q.evaluation.score !== undefined)
    .map(q => q.evaluation!.score!);
  
  if (validScores.length === 0) return 0;
  
  const average = validScores.reduce((sum, score) => sum + score, 0) / validScores.length;
  if (this.overallEvaluation) {
    this.overallEvaluation.averageScore = Math.round(average * 100) / 100;
  }
  return this.overallEvaluation?.averageScore || 0;
};

// Pre-save hook to update completed status and duration
interviewSessionSchema.pre('save', function(next) {
  if (this.isModified('status') && this.status === 'completed' && !this.completedAt) {
    this.completedAt = new Date();
  }
  
  if (this.startedAt && this.completedAt) {
    this.totalDuration = Math.round((this.completedAt.getTime() - this.startedAt.getTime()) / (1000 * 60));
  }
  
  next();
});

const InterviewSession: Model<IInterviewSession> = mongoose.models.InterviewSession || mongoose.model<IInterviewSession>('InterviewSession', interviewSessionSchema);

export default InterviewSession;
